Add script to manage solver authentication (gnosis/gp-v2-contracts#282)
Implements basic management of the solver authentication list. The owner is now a real address: the private key is stored in our shared secret management system as "[DEV] Rinkeby GPv2 authenticator owner".

Three new commands have been implemented:
1. `yarn solvers add $ADDRESS`
2. `yarn solvers remove $ADDRESS`
3. `yarn solvers check $ADDRESS`

Adding and removing can only be done if the private key of the owner is loaded.

The contracts have been redeployed with the new owner.

### Test Plan

This is what I ran on the [currently deployed contract](https://rinkeby.etherscan.io/address/0x60027a9c1ef06ee9890f086b05a4acc6cd041d62). You could verify that the first three transactions correspond to what I wrote below.

```
bash>$ unset PK MNEMONIC
bash>$ yarn --silent solvers check 0x0000000000000000000000000000000000000001 --network rinkeby
0x0000000000000000000000000000000000000001 is NOT a solver.
bash>$ yarn --silent solvers add 0x0000000000000000000000000000000000000001 --network rinkeby
An unexpected error occurred:

Error: No owner found among the signers. Did you export the owner's private key?
    at getOwnerSigner (/repo/oba-contracts/src/tasks/solvers.ts:26:11)
    <snip>
bash>$ export PK='redacted'
bash>$ yarn --silent solvers check 0x1111111111111111111111111111111111111142 --network rinkeby
0x1111111111111111111111111111111111111142 is NOT a solver.
bash>$ yarn --silent solvers add 0x1111111111111111111111111111111111111142 --network rinkeby # https://rinkeby.etherscan.io/tx/0xa90aa78c666a15e2c8779480c1a44a8c1d89f6b2f97159386a2b33565f4ad178
Solver added.
bash>$ yarn --silent solvers check 0x1111111111111111111111111111111111111142 --network rinkeby
0x1111111111111111111111111111111111111142 is a solver.
bash>$ yarn --silent solvers remove 0x1111111111111111111111111111111111111142 --network rinkeby # https://rinkeby.etherscan.io/tx/0xd2aec1539ab38fd9cff81b0263a0ac1c29136cee9dbb6ccd4485bf99c5aa9364
Solver removed.
bash>$ yarn --silent solvers check 0x1111111111111111111111111111111111111142 --network rinkeby
0x1111111111111111111111111111111111111142 is NOT a solver.
bash>$ yarn --silent solvers add 0x0000000000000000000000000000000000000042 --network rinkeby # https://rinkeby.etherscan.io/tx/0xed3d3cab7c040d63987b26812c2deb96f5e6cd5c4e0f0a5568145272fa89d406
Solver added.
```

You can check that `0x00..42` is still an owner with `yarn --silent solvers check 0x0000000000000000000000000000000000000042 --network rinkeby`.

You can also run the same instructions with a newly deployed version of the contract (delete the content of the `deployments/rinkeby` folder to avoid address mismatched). Note that these scripts cannot be tested on the Hardhat network since the state of the blockchain is reset after each execution of Hardhat, meaning that no contracts are available when running the scripts there.