Bump to latest Ethers and switch to EIP-712 signatures (gnosis/gp-v2-contracts#875)
This PR bumps Ethers.js to the latest version.

Note that it required changing the signing scheme to EIP-712. This is because it appears that Ethers + Hardhat `eth_sign` signatures are currently broken (https://github.com/nomiclabs/hardhat/issues/1981). This is because they recently changed to always use `personal_sign` for `signMessage` calls (https://github.com/ethers-io/ethers.js/commit/8947fd405e3aea07f6db958d89a3ad39abe3a25a), which isn't supported by Hardhat:
```
     MethodNotFoundError: Method personal_sign not found
```

Note that we had previously used `eth_sign` signatures because EIP-712 signatures were broken with hardhat, but this should no longer be the case (https://github.com/nomiclabs/hardhat/pull/1346).

### Test Plan

CI still passes.