Add standard networks to Hardhat config (gnosis/gp-v2-contracts#157)
Configure Mainnet, Rinkeby, and Xdai networks for this repo.

The configuration is basically the usual one for Gnosis repos ported to Hardhat.

### Test Plan

Create the following `test.ts` file at the root of the repo.

<details><summary>test.ts</summary>

```
import hardhat, { ethers } from "hardhat";

(async () => {
  console.log("Network:", hardhat.network.name);
  const balanceWethMainnet = await ethers.provider.getBalance(
    "0xc02aaa39b223fe8d0a0e5c4f27ead9083c756cc2",
  );
  const balanceWethRinkeby = await ethers.provider.getBalance(
    "0xc778417e063141139fce010982780140aa0cd5ab",
  );
  const balanceWethXdai = await ethers.provider.getBalance(
    "0xe91d153e0b41518a2ce8dd3d7944fa863463a97d",
  );
  console.log("Mainnet WETH address:", balanceWethMainnet.toString());
  console.log("Rinkeby WETH address:", balanceWethRinkeby.toString());
  console.log("Xdai wxDAI address:", balanceWethXdai.toString());
  console.log(
    "Accounts:",
    (await ethers.getSigners()).slice(0, 3).map((thing) => thing.address),
  );
})();

```
</details>
It takes the three addresses of the three "wrapping" contract in the three different networks and prints their balances. The expectation is that the wrapping address of the used network has the highest balance of the three.
It also prints the account addresses.



To test the new configs, insert your Infura key where needed and run the following block of code, comparing each output with that line's comment.
```
unset INFURA_KEY PK MNEMONIC
npx hardhat run test.ts # test network, no balances
npx hardhat run test.ts --network xdai # wxDAI has highest balance, also some dust at WETH address. Using addresses from default mnemonic.
npx hardhat run test.ts --network rinkeby # error: no Infura key
npx hardhat run test.ts --network mainnet # error: no Infura key
export INFURA_KEY='insert your Infura key here'
npx hardhat run test.ts --network rinkeby # Rinkeby WETH has highest balance, also some dust at WETH address.
npx hardhat run test.ts --network mainnet # Only mainnet WETH has funds
export MNEMONIC="treat candy maple cake sugar pudding cream honey rich smooth crumble sweet"
npx hardhat run test.ts --network mainnet # Different addresses from before
export PK="0000000000000000000000000000000000000000000000000000000000000001"
npx hardhat run test.ts --network mainnet # Only one address
```


<details><summary>Actual output</summary>

```
bash>$ unset INFURA_KEY PK MNEMONIC
bash>$ npx hardhat run test.ts # test network, no balances
Network: hardhat
Mainnet WETH address: 0
Rinkeby WETH address: 0
Xdai wxDAI address: 0
Accounts: [
  '0xf39Fd6e51aad88F6F4ce6aB8827279cffFb92266',
  '0x70997970C51812dc3A010C7d01b50e0d17dc79C8',
  '0x3C44CdDdB6a900fa2b585dd299e03d12FA4293BC'
]
bash>$ npx hardhat run test.ts --network xdai # wxDAI has highest balance, also some dust at WETH address. Using addresses from default mnemonic.
Network: xdai
Mainnet WETH address: 43533800000000000000
Rinkeby WETH address: 0
Xdai wxDAI address: 990022947559257776101545
Accounts: [
  '0x627306090abaB3A6e1400e9345bC60c78a8BEf57',
  '0xf17f52151EbEF6C7334FAD080c5704D77216b732',
  '0xC5fdf4076b8F3A5357c5E395ab970B5B54098Fef'
]
bash>$ npx hardhat run test.ts --network rinkeby # error: no Infura key
An unexpected error occurred:

Error: Could not find Infura key in env, unable to connect to network rinkeby
    at Object.<anonymous> (/repo/oba-contracts/hardhat.config.ts:35:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/repo/oba-contracts/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/repo/oba-contracts/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at importCsjOrEsModule (/repo/oba-contracts/node_modules/hardhat/src/internal/core/config/config-loading.ts:18:20)
bash>$ npx hardhat run test.ts --network mainnet # error: no Infura key
An unexpected error occurred:

Error: Could not find Infura key in env, unable to connect to network mainnet
    at Object.<anonymous> (/repo/oba-contracts/hardhat.config.ts:35:9)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Module.m._compile (/repo/oba-contracts/node_modules/ts-node/src/index.ts:1043:23)
    at Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Object.require.extensions.<computed> [as .ts] (/repo/oba-contracts/node_modules/ts-node/src/index.ts:1046:12)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at importCsjOrEsModule (/repo/oba-contracts/node_modules/hardhat/src/internal/core/config/config-loading.ts:18:20)
bash>$ export INFURA_KEY='redacted'
bash>$ npx hardhat run test.ts --network rinkeby # Rinkeby WETH has highest balance, also some dust at WETH address.
Network: rinkeby
Mainnet WETH address: 657426185560000000034
Rinkeby WETH address: 24387565362859636294142
Xdai wxDAI address: 0
Accounts: [
  '0x627306090abaB3A6e1400e9345bC60c78a8BEf57',
  '0xf17f52151EbEF6C7334FAD080c5704D77216b732',
  '0xC5fdf4076b8F3A5357c5E395ab970B5B54098Fef'
]
bash>$ npx hardhat run test.ts --network mainnet # Only mainnet WETH has funds
Network: mainnet
Mainnet WETH address: 6186641465995370328609141
Rinkeby WETH address: 0
Xdai wxDAI address: 0
Accounts: [
  '0x627306090abaB3A6e1400e9345bC60c78a8BEf57',
  '0xf17f52151EbEF6C7334FAD080c5704D77216b732',
  '0xC5fdf4076b8F3A5357c5E395ab970B5B54098Fef'
]
bash>$ export MNEMONIC="treat candy maple cake sugar pudding cream honey rich smooth crumble sweet"
bash>$ npx hardhat run test.ts --network mainnet # Different addresses from before
Network: mainnet
Mainnet WETH address: 6186643977039666072621705
Rinkeby WETH address: 0
Xdai wxDAI address: 0
Accounts: [
  '0x70A15E8b667afb0cDbbCB7F905Beb8E1d287180A',
  '0xE4cd9C0D7949e1bd01aE12168081124Ab7192640',
  '0x730aF1042a376C69241dA8f0C6cC9CaF0Fc08BE1'
]
bash>$ export PK="0000000000000000000000000000000000000000000000000000000000000001"
bash>$ npx hardhat run test.ts --network mainnet # Only one address
Network: mainnet
Mainnet WETH address: 6186643977039666072621705
Rinkeby WETH address: 0
Xdai wxDAI address: 0
Accounts: [ '0x7E5F4552091A69125d5DfCb7b8C2659029395Bdf' ]
bash>$

```
</details>