Frist npm release to depend on package in gp-v2-services (gnosis/gp-v2-contracts#215)
As title. While doing this I noticed we are not yet compiling our typescript code and when trying to add it I saw a bunch of compilation errors:

<details><summary>Details</summary>

```
felixleupold@Felixs-MBP oba-contracts 15:19 [2]$ yarn tsc
yarn run v1.22.10
$ /Users/felixleupold/Gnosis/oba-contracts/node_modules/.bin/tsc
src/deploy/001_authenticator.ts:7:3 - error TS2339: Property 'deployments' does not exist on type 'HardhatRuntimeEnvironment'.

7   deployments,
    ~~~~~~~~~~~

src/deploy/001_authenticator.ts:8:3 - error TS2339: Property 'getNamedAccounts' does not exist on type 'HardhatRuntimeEnvironment'.

8   getNamedAccounts,
    ~~~~~~~~~~~~~~~~

src/deploy/002_settlement.ts:7:3 - error TS2339: Property 'deployments' does not exist on type 'HardhatRuntimeEnvironment'.

7   deployments,
    ~~~~~~~~~~~

src/deploy/002_settlement.ts:8:3 - error TS2339: Property 'getNamedAccounts' does not exist on type 'HardhatRuntimeEnvironment'.

8   getNamedAccounts,
    ~~~~~~~~~~~~~~~~

src/ts/deploy.ts:2:10 - error TS2305: Module '"../../node_modules/hardhat/internal/lib/hardhat-lib"' has no exported member 'ethers'.

2 import { ethers } from "hardhat";
           ~~~~~~


Found 5 errors.
```

</details>

We can address those in this PR and republish, or leave them to another PR.  Building and type-checking our code on every commit is probably a good step to include into travis.

### Test Plan

https://www.npmjs.com/package/@gnosis.pm/gp-v2-contracts